language: rust

rust:
  - 1.17.0 # ~4 releases behind latest stable
  - stable
  - beta
  - nightly

cache: cargo

matrix:
  allow_failures:
    - rust: nightly

  include:
    - rust: stable
      sudo: required
      script:
        - bash <(curl -s https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
        - cargo tarpaulin --out Xml
        - bash <(curl -s https://codecov.io/bash) -Z -f cobertura.xml
