[package]
name = "version-sync"
version = "0.4.0"
authors = ["Martin Geisler <martin@geisler.net>"]
description = """
Simple crate for ensuring that version numbers in README files are
updated when the crate version changes.
"""
documentation = "https://docs.rs/version-sync/"
repository = "https://github.com/mgeisler/version-sync"
readme = "README.md"
keywords = ["version"]
categories = ["development-tools", "rust-patterns"]
license = "MIT"
exclude = [".dir-locals.el"]

[badges]
travis-ci = { repository = "mgeisler/version-sync" }
appveyor = { repository = "mgeisler/version-sync" }

[dependencies]
pulldown-cmark = { version = "0.0.11", default-features = false }
semver-parser = "0.7"
syn = { version = "0.11", features = ["full"] }
toml = "0.4"
url = "1.5.1"
# unicode-bidi is an indirect dependency and version 0.3.4 is not
# compatible with Rust 1.15.0:
unicode-bidi = "0.3.1, < 0.3.4"
itertools = "0.6.3"
