[package]
name = "check-versions"
version = "0.1.0"
authors = ["Martin Geisler <martin@geisler.net>"]

[dependencies]
pulldown-cmark = { version = "0.0.11", default-features = false }
semver-parser = "0.7"
toml = "0.4"
