[package]
name = "check-versions"
version = "0.1.2"
authors = ["Martin Geisler <martin@geisler.net>"]
description = """
Simple crate for ensuring that version numbers in README files are
updated when the crate version changes.
"""
documentation = "https://docs.rs/check-versions/"
repository = "https://github.com/mgeisler/check-versions"
readme = "README.md"
keywords = ["version"]
categories = ["development-tools", "rust-patterns"]
license = "MIT"

[dependencies]
pulldown-cmark = { version = "0.0.11", default-features = false }
semver-parser = "0.7"
toml = "0.4"
